spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeff?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
mybatis-plus:
  type-aliases-package: com.jeff.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
    com.jeff.mapper: DEBUG